# Configuration for Underwater Network Simulation
simulation:
  evaluation_ranges_m: [1, 10, 15, 50, 100, 500, 1000, 3000]
  visualization:
    range_labels: ["1m", "10m", "15m", "50m", "100m", "500m", "1km", "3km"]
    figure_size: [16, 9]
    bar_width: 0.25
    y_axis_limits: [-20, 130]
    snr_clamp_threshold_db: -10.0
    style: "seaborn-v0_8-whitegrid"
    output_path: "snr_comparison_chart.png"

environment:
  wind_speed_ms: 5.0
  shipping_factor: 0.5 # 0=low, 1=high

physical_layer:
  mi:
    transmit_power_watts: 0.05
    calibration:
      max_range_m: 15.0
      snr_at_max_range_db: 3.0
  acoustic:
    center_frequency_khz: 18.0
    bandwidth_hz: 3000.0
    default_transmit_power_watts: 5.0
    spreading_factor: 1.5